name: Publish to main
'on':
  schedule:
    - cron: '*/30 * * * *'
  workflow_dispatch:
    inputs:
      ref:
        description: The Operator branch/tag to checkout when creating the image.
        required: true
        default: release_operator_image
      prev_version:
        description: The Operator version to replace
env:
  GITHUB_TOKEN: '${{ secrets.MY_TOKEN }}'
  release-version: '${{ github.event.inputs.ref }}'
  replace_version: '${{ github.event.inputs.prev_version }}'
jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - name: Configure Git
        run: |
          git config --global user.name "pminz"
          git config --global user.email "pminz@redhat.com"
      - name: Checkout
        uses: actions/checkout@v2
        with:
          path: operator
    env:
      DELAYED_JOB_CHECKOUT_REF: 41e57b9447595a6fd76e42afaa3ff0509403747d
      DELAYED_JOB_CHECKOUT_REF_IS_TAG: 'false'
      DELAYED_JOB_WORKFLOW_FILE_PATH: .github/workflows/publish-main.yaml
      DELAYED_JOB_WORKFLOW_UNSCHEDULE_TARGET_BRANCH: main
