name: Trigger workflow for release

on:
  workflow_dispatch:
    inputs:
      cache-manager-ref:
        type: string
        default: main
      cache-manager-repository:
        type: string
        default: gingersnap-project/cache-manager
      db-syncer-ref:
        type: string
        default: main
      db-syncer-repository:
        type: string
        default: gingersnap-project/db-syncer
    

jobs:

  trigger-workflow:
    uses: gingersnap/release/.github/workflows/trigger-build.yaml@release_workflow
    with:
      db-syncer-ref: ${{ inputs.db-syncer-ref }}