name: 'Trigger release.yaml of all components'
on:
 push:
   branches:
     - 'trigger_workflow'
# workflow_dispatch:
#   inputs:
#     ref:
#       description: "The release branch/tag to checkout when triggering the workflow."
#       required: true
#       default: "release_branch"

env:
  GITHUB_TOKEN: ${{ secrets.PAT_TOKEN }}   
  ref: main

jobs:
#  build:
#    runs-on: ubuntu-latest
#    steps:
#      - name: Main workflow
#        run: |
#          echo "Dummy job to run dispatch job"
          
  dispatch:
#    needs: build
    strategy:
      matrix:
        repo: ['pminz/operator']
    runs-on: ubuntu-latest
    steps:
      - name: Repository Dispatch
        uses: peter-evans/repository-dispatch@v2
        with:
          token: ${{ secrets.MY_TOKEN }}
          repository: ${{ matrix.repo }}
          event-type: my-event
          client-payload: '{"ref": "${{ env.ref }}"}'