name: Trigger workflow for release

on:
  workflow_dispatch:
    inputs:
      db-syncer-ref:
        type: string
        default: main
      db-syncer-repository:
        type: string
        default: pminz/db-syncer
      ref: 
        type: string
        default: release_workflow
        
    

jobs:

  trigger-workflow:
    uses: gingersnap/release/.github/workflows/trigger-build.yaml@\"${{inputs.ref}}\"
    with:
      db-syncer-ref: ${{ inputs.db-syncer-ref }}