name: Trigger workflow for release

on:
  workflow_call:
    inputs:
      cache-manager-ref:
        type: string
        default: main
      cache-manager-repository:
        type: string
        default: gingersnap-project/cache-manager
      db-syncer-ref:
        type: string
        default: main
      db-syncer-repository:
        type: string
        default: gingersnap-project/db-syncer
      operator-ref:
        type: string
        default: main
      operator-repository:
        type: string
        default: gingersnap-project/operator

jobs:

  check-images:
    uses: pminz/db-syncer/.github/workflows/test_create_tag.yaml@workflow_call
    with: 
      ref: ${{ inputs.db-syncer-ref }}
      repo: ${{ inputs.db-syncer-repository }}
  
  operator: 
    runs-on: ubuntu-latest
    if: success()
    needs: check-images
    steps:
      - name: Configure Git
        run: |
          echo "last job was successful"