name: Trigger workflow for release

on:
  workflow_dispatch:
    inputs:
      operator-ref:
        type: string
        default: main
      operator-repository:
        type: string
        default: gingersnap-project/operator
      tag:
         type: string
         default: latest 

jobs:
  
  operator: 
    uses: pminz/operator/.github/workflows/release.yaml@test_checkout
    secrets: inherit
    with:
      ref: ${{ inputs.operator-ref }}
      repository: ${{ inputs.operator-repository }}
      tag: ${{ inputs.tag }